[package]
name = "rsvg"
version = "0.1.0"
authors = ["selaux"]
categories = ["api-bindings", "svg"]
description = "Rust bindings for the Rsvg library"
repository = "https://github.com/selaux/rsvg-rs"
license = "LGPL"

keywords = ["svg", "gtk-rs", "gnome"]

[lib]
name = "rsvg"

[dependencies]
libc = "0.2"
bitflags = "0.5"

[dev-dependencies]
image = "0.13.0"
imageproc = "0.8.0"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.1"

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/cairo"
version = "0.1.1"
features = ["png"]

[dependencies.gdk-pixbuf]
git = "https://github.com/gtk-rs/gdk-pixbuf"
version = "0.1.1"

[dependencies.rsvg-sys]
path = "./rsvg-sys"
version = "0.3.2"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.2"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.2"
