[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
bitflags = "0.8"
libc = "0.2"

[dependencies.atk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/cairo"
version = "0.3.4"

[dependencies.gdk-pixbuf-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.gdk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[dependencies.pango-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.4"

[lib]
name = "rsvg_sys"

[package]
build = "build.rs"
links = "rsvg"
name = "rsvg-sys"
version = "0.3.4"
